name: Deploy to web
on:
  push:
    branches: [main]
permissions:
  contents: write
jobs:
  create-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Install and build
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      - name: Build project
        run: |
          npm install
          yarn run build
   
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build
          ssh-key: ${{ secrets.DEPLOY_KEY }}